image: maven:3.8.4-openjdk-11-slim

stages:
  - build
  - test

build:
  stage: build
  script:
    - mvn -DskipTests package
  artifacts:
    paths:
      - "**/target/*.jar"

test:
  stage: test
  script:
    - mvn test
